services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:7-jammy
    container_name: taskmanager-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tasksmanagerbd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Backend API .NET
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDb: mongodb://admin:password123@mongodb:27017/tasksmanagerbd?authSource=admin
      JWT__SecretKey: TaskManager2025-SecretKey-256bits-Required-For-HS256-Docker-Key
      JWT__Issuer: TaskManager
      JWT__Audience: TaskManagerUsers
      JWT__ExpirationInHours: 24
      UseConsoleEmail: true
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    restart: unless-stopped
    environment:
      API_URL: http://backend:8080
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - taskmanager-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
    driver: local

networks:
  taskmanager-network:
    driver: bridge